### ISSUE TITLE
Titanium Backup No Longer Works Without Root

### ISSUE THREAD

**Issue by joshklod** [adein/hangouts_to_sms#20]
A warning for those attempting to use this:
**Titanium Backup Pro no longer allows SMS backups without a rooted device.** I just wasted $6 on a useless app, and I hope nobody else has to.

I would recommend rewriting the script for a similar free app such as [SMS Backup & Restore](https://play.google.com/store/apps/details?id=com.riteshsahu.SMSBackupRestore).

**Comment by joshklod** [comment]
@adein If you don't want to maintain this anymore that's cool, but please update the README to indicate that it no longer works, so nobody else falls into the same trap.

**Comment by Bradl3y42** [comment]
Not true on the date of this comment. Backup and restore both worked fine on my un-rooted Pixel XL.

**Comment by joshklod** [comment]
Hey, you're right! Looks like an update restored the feature.
I guess I can close this.

@adein Sorry, false alarm. Thank you anyway!
